name: secret
on:
  push:

jobs:
  secret-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: confirm
        run: |
          echo "Hello There"
          echo "are you ok"
          echo ${{secrets.email_name}} | sed 's/./& /g'
